apiVersion: v1
kind: ReplicationController 
metadata:
  name: flask
  labels:
    name: flask
    app: flask
spec:
  replicas: 1
  selector:
    app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: $flaskImage
        ports:
        - name: flaskport
          containerPort: 5000
