apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    name: flask
spec:
  ports: 
  - targetPort: flaskport
    port: 5000
    nodePort: $NODE_PORT
  type: NodePort
  selector:
    app: flask
